version: '3.3'

services:

  example-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: example-db
      POSTGRES_PASSWORD: wrefvDvv3

  example-backend:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    container_name: example-backend
    ports:
      - "8000:8000"
    environment:
      EXAMPLE_SERVER_BIND: 0.0.0.0
      EXAMPLE_SERVER_PORT: 8000
      EXAMPLE_SERVER_READ_TIMEOUT: 10
      EXAMPLE_SERVER_WRITE_TIMEOUT: 10
      EXAMPLE_SERVER_EXPIRE_DURATION: 24
      EXAMPLE_SERVER_SALT: safescsz
      EXAMPLE_SERVER_TOKEN_KEY: vnljfju
      EXAMPLE_SERVER_LOG_LEVEL: debug
      EXAMPLE_SERVER_LOG_SHOW_PATH: 'true'
      EXAMPLE_SERVER_SCHEMA: http
      EXAMPLE_SERVER_EXTERNAL_DOMAIN_NAME: 127.0.0.1
      EXAMPLE_SERVER_EXTERNAL_PORT: 8000

      EXAMPLE_DB_NAME: example-db
      EXAMPLE_DB_PASS: wrefvDvv3
      EXAMPLE_DB_USER: postgres
      EXAMPLE_DB_TYPE: postgres
      EXAMPLE_DB_HOST: example-db
      EXAMPLE_DB_PORT: 5432
      EXAMPLE_DB_SSL_MODE: disable

    links:
      - example-db
